# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
- main

schedules:
  - cron: "10 * * * *"
    displayName: Check run hourly
    branches:
      include:
        - main
    always: 'true'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a cron job'

- task: Bash@3
  inputs:
   targetType: 'inline'
   script: |
     ./urlcheck.sh
   failOnStderr: true
   workingDirectory: "/home/vsts/work/1/s/"